---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates a self-healing Bamboo server using Chef

Parameters:

  FQDN:
    Type: String
    Default: bamboo.randall-it.uk
    Description: DNS name to create for the Bamboo server

  ImageId:
    Type: String
    Description: ImageId to use for the Bamboo server

  InstanceType:
    Type: String
    Default: t2.small
    Description: InstanceType to use for the Bamboo server

  HostedZoneId:
    Type: String
    Default: Z35V1WYGMHE3VE
    Description: Route 53 hosted zone in which the Bamboo server will create a record

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: dave
    Description: KeyName to use for the Bamboo server

  PublicIpAddress:
    Type: String
    Description: Public IP address that the Bamboo server will be accessible from

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A list of subnets in which to launch the Bamboo server

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: A VPC in which to create resources

Resources:

  # Launch configuration defines the instance properties
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: True
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: True
            VolumeSize: 8
            VolumeType: gp2
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Join
          - "\n"
          - - "yum install -y epel-release"
            - "yum install -y python-pip wget rubygems"
            - "pip install awscli"
            - "wget https://packages.chef.io/files/stable/chef/12.18.31/el/7/chef-12.18.31-1.el7.x86_64.rpm"
            - "rpm -Uvh chef-12.18.31-1.el7.x86_64.rpm"
            - !Join ["", ["aws s3 cp s3://", !ImportValue "chef-bucket", "/validator.pem ~"]]
            - !Join ["", ["aws s3 cp s3://", !ImportValue "chef-bucket", "/client.rb ~"]]
            - !Join ["", ["aws s3 cp s3://", !ImportValue "chef-bucket", "/bamboo-record.json ~"]]
            - "echo '{\"run_list\": [\"role[bamboo]\"]}' > /etc/chef/first-boot.json"
            - "chef-client -j /etc/chef/first-boot.pem"
            - "PUBLIC_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)"
            - !Join ["", ["sed -i -e \"s/FQDN-HERE/", !Ref FQDN, "/g\" ~/bamboo-record.json"]]
            - "sed -i -e \"s/IP-ADDRESS-HERE/$PUBLIC_IP/g\" ~/bamboo-record.json"
            - !Join ["", ["aws route53 change-resource-record-sets --hosted-zone-id ", !Ref HostedZoneId, " --change-batch file://~/bamboo-record.json"]]
            - "rm ~/* -f"

  # Instance profile allows the instances to assume a role
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: InstanceRole
    Properties:
      Roles:
        - !Ref InstanceRole

  # Instance role that allows the instance to perform various tasks defined in policies
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
        Version: 2012-10-17
      Path: "/"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                - s3:GetBucketLocation
                - s3:ListBucket
                Effect: Allow
                Resource: !Join ["", ["arn:aws:s3:::", !ImportValue "chef-bucket"]]
          PolicyName: chef-bucket-root
        - PolicyDocument:
            Statement:
              - Action: s3:GetObject
                Effect: Allow
                Resource: !Join ["", ["arn:aws:s3:::", !ImportValue "chef-bucket", "/*"]]
          PolicyName: chef-bucket-contents
        - PolicyDocument:
            Statement:
              - Action: route53:ChangeResourceRecordSets
                Effect: Allow
                Resource: !Join ["", ["arn:aws:route53:::hostedzone/", !Ref HostedZoneId]]
          PolicyName: route53-record

  # A security group that allows access to the Bamboo server over port 8085 from a specific IP
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows access to the Bamboo server from Randall IT
      SecurityGroupIngress:
        - CidrIp: !Join ["", [!Ref PublicIpAddress, "/32"]]
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: !Join ["", [!Ref PublicIpAddress, "/32"]]
          FromPort: 8085
          IpProtocol: tcp
          ToPort: 8085
      Tags:
        - Key: Name
          Value: randall-it-private-bamboo
      VpcId: !Ref VpcId

  # An autoscaling group which will launch the desired number of Bamboo servers
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 1
      MinSize: 0
      VPCZoneIdentifier: !Ref SubnetIds
